version: "3.3"

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - COMMAND=http
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
    networks:
      - pismo
    env_file:
      - .env
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/data/postgres
    networks:
      - pismo

volumes:
  postgres:
networks:
  pismo:
