version: "3.3"

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - COMMAND=http
    volumes:
      - .:/src/app
    ports:
      - "5000:8080"
    networks:
      - pismo
    env_file:
      - .env
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
networks:
  pismo:
