version: "3.3"

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - COMMAND=http
    volumes:
      - .:/src/app
    ports:
      - "5000:8080"
    networks:
      - pismo
    env_file:
      - .env

networks:
  pismo:
