// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package queries

import (
	"time"
)

type Account struct {
	ID       int64
	Document string
}

type OperationType struct {
	ID          int64
	Description string
	Type        string
}

type Transaction struct {
	ID              int64
	AccountID       int64
	OperationTypeID int64
	Amount          float32
	EventDate       time.Time
}
