basePath: /v2
host: petstore.swagger.io
info:
  contact:
    email: tiagofvx@gmail.com
    name: Tiago braga
    url: http://www.swagger.io/support
  description: This is a sample transactions api.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Transactions API
  version: "1.0"
paths: {}
swagger: "2.0"
